// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABO9iPedLA8pGHaQBxq7kQsGMF5YXyl_0',
    appId: '1:995888910087:web:d8c2a8e4e632850808bfa2',
    messagingSenderId: '995888910087',
    projectId: 'discograde0901',
    authDomain: 'discograde0901.firebaseapp.com',
    storageBucket: 'discograde0901.firebasestorage.app',
    measurementId: 'G-CT9GFH6D80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCBNMe_nyMkLbST20KZDtvcuQy2pgC0nE',
    appId: '1:995888910087:android:e2320d841438e9f508bfa2',
    messagingSenderId: '995888910087',
    projectId: 'discograde0901',
    storageBucket: 'discograde0901.firebasestorage.app',
  );
}
